version: '3'

services:
    app:
        build: ./docker/app
        volumes:
            - ./:/var/www/html:cached
            - app-session:/var/www/html/var/sessions
            - app-log:/var/www/html/var/logs
            - apache-log:/var/log/apache2
            - ./docker/app/apache2/sites-enabled/app.conf/:/etc/httpd/conf.d/app.conf:cached
            - ./docker/app/php-fpm/conf/custom-php.ini:/etc/php.d/custom-php.ini:cached
        ports:
            - 8080:80

    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=tapasvu
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8081:80
        depends_on:
          - db

volumes:
  app-session: {}
  app-log: {}
  apache-log: {}
  db_data: {}
