# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        main:
            anonymous: ~
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
            logout:
                path:   /logout
                target: /
            form_login:
                login_path: login
                check_path: login
                default_target_path: after_login_route_name
                always_use_default_target_path: true
                use_referer: true
                failure_path: login_failure_route_name

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin/users, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

